### Testing the environment, connecting to psql running locally
POST http://localhost:5001/register
Content-Type: application/json

{
    "username": "joeyvico@gmail.com",
    "password": "quicksilver74"
}