### Testing the environment, connecting to psql running locally
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "joeyvico@gmail.com",
    "password": "quicksilver74"
}
###  Passing empty data  to test backend's validation
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###  connecting to psql running locally
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "sonoya@gmail.com",
    "password": "quicksilver78"
}

###  connecting to psql running locally
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "dummy@gmail.com",
    "password": "quicksilver74"
}

#### Docker container running api, exposed port 80
### Incoming port defined in the docker run command
POST http://localhost:49160/auth/login
Content-Type: application/json

{
    "email": "joeyvico@gmail.com",
    "password": "quicksilver74"
}

### Incoming 
GET http://localhost:49160/weatherforecast
