### Reset password
POST http://localhost:5000/auth/resetpassword
Content-Type: application/json

{
    "email": "joeyvico@gmail.com",
    "password": "quicksilver74"
}

### Reset password
POST http://localhost:5000/auth/resetpassword
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2V5dmljb0BnbWFpbC5jb20iLCJleHAiOjE2MDQwMTQ2NzEsImlzcyI6ImpvZXl2aWNvQGdtYWlsLmNvbSIsImF1ZCI6ImpvZXl2aWNvQGdtYWlsLmNvbSJ9.0GFbx-qLdasx_dmMTXgQc46Q-ahQ_tFmShe7beNttQ1gUcqErpmfdo3Hrg4sVKbiOk30HjVQf36O6ATEitM_OQ
Content-Type: application/json

{
    "email": "sonoya@gmail.com",
    "password": "quicksilver78"
}